version: '3.9'

services:
  laravel:
    container_name: laravel
    build:
      context: ./laravel-app
      dockerfile: Dockerfile
    volumes:
      - ./laravel-app:/var/www/html
    environment:
      DB_HOST: mysql
      DB_PASSWORD: root
    ports:
      - '8000:8000'
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    container_name: mysql
    image: mysql:8.1.0-oracle
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news_n_article
      MYSQL_PASSWORD: root

    networks:
      - app_network

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app_network

  reactjs:
    container_name: reactjs
    build:
      context: ./react-app
      dockerfile: Dockerfile
    volumes:
      - ./react-app:/app/react
    tty: true
    ports:
      - '3000:3000'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
